FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install -r ./requirements.txt

COPY main.py ./
EXPOSE 8081

CMD opentelemetry-instrument \
    --traces_exporter console,otlp \
    --metrics_exporter console \
    --service_name your-service-name \
    --exporter_otlp_endpoint 0.0.0.0:4317 \
    uvicorn main:app --host 0.0.0.0 --port 8081 --reload
