global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: API
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8080']
  - job_name: LatencyWatcher
    metrics_path: '/metrics'
    static_configs:
      - targets: ['latency_watcher:8090']
