global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: Golang 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['golang:8080']
  - job_name: Python
    metrics_path: '/metrics'
    static_configs:
      - targets: ['python:8081']
